version: "3.9"

services:
  sac:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
  postgres:
    image: "postgres:11-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sac_db
    ports:
      - "5432:5432"
